### ISSUE TITLE
Undefined reference to initrenpy_gl_gl

### ISSUE THREAD

**Issue by dogtopus** [renpy/renpyweb#10]
Since renpy/renpy@ddb8c8c068a983875914fcbfc042ed7f0dbce729 there's no `renpy.gl.gl` anymore so the `initrenpy_gl_gl` definition in `main.c` causes link error.

**Comment by Beuc** [comment]
Ren'Py is currently a moving target with a couple refactoring underway, so RenPyWeb works with the stable version (7.3.5).
(Please don't open an issue anytime Ren'Py master fails.)

**Comment by dogtopus** [comment]
I figured. Maybe add a notice on the README that only the latest release version is supported and modify the script accordingly so people who wants to build renpyweb don't spend hours debugging like me?
